// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dataspace-lookups/Compact.tsx": () => import("../components/mockups/dataspace-lookups/Compact.tsx"),
  "./components/mockups/dataspace-lookups/Current.tsx": () => import("../components/mockups/dataspace-lookups/Current.tsx"),
  "./components/mockups/osdu-kind-breakdown/Compact.tsx": () => import("../components/mockups/osdu-kind-breakdown/Compact.tsx"),
  "./components/mockups/osdu-kind-breakdown/Current.tsx": () => import("../components/mockups/osdu-kind-breakdown/Current.tsx")
};
